name: Build Step

on:
  push:
    branches: ['main'] # This runs the full pipeline *after* a merge to 'main'

  pull_request:
    branches: [ "main" ] # This triggers pre-merge checks for PRs into 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v18.17.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

  test-stage:
    runs-on: ubuntu-latest
    needs: build # Ensures tests run after a successful build
    steps:
      - name: Running Tests
        uses: actions/checkout@v3
      - run: echo "running tests..." # Replace with your actual test command

  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    needs: ['build', 'test-stage']
    # This 'if' condition is the key. It ensures this job only runs if:
    # 1. The event is a 'push' (not a 'pull_request') AND
    # 2. The branch being pushed to is 'main'.
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.ARGO_USER }}
          password: ${{ secrets.G_TOKEN }}
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            123saketh/argoreactapp:${{ github.sha }}
            ghcr.io/123saketh/argoreactapp:${{ github.sha }}
          push: true
          build-args: |
            PUBLIC_URL=/react-app
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: ['build-and-push-docker-image']
    # This 'if' condition is similar, ensuring this job only runs if:
    # 1. The event is a 'push' (not a 'pull_request') AND
    # 2. The branch being pushed to is 'main'.
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 123saketh/argoinfra
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}
      - name: setup git config
        run: |
          git config --global user.email "${{secrets.ARGO_EMAIL}}"
          git config --global user.name "${{secrets.ARGO_USER}}"
      - name: Update Deployment YAML
        run: |
          echo ${{ github.sha }}
          sed -i "s#${{ github.actor }}.*#123saketh/argoreactapp:${{ github.sha }}#g" react-app/deployment.yaml
      - name: Commit and Push Changes
        run: |
          git add -A
          git commit -am "Update image for - ${{ github.sha }}"
          git push origin main
